### PR TITLE
Battery Service : Add support for turbo power 

### PR DESCRIPTION
**Pull request by sri-sandeep108**
This is a commit inspired from the Dash charging commit .... Verified and tested

### CODE REVIEW

**Comment by sri-sandeep108** [comment]
@sandyorton7 @sagarshah1729 take a look at em and merge em Sur ;___;

**Comment by sagarshah1729** [comment]
Link me the original commit from where you picked it. Authorship needs to be maintained.

**Comment by Keertesh19** [comment]
@sagarshah1729 Here we go https://github.com/rr-upstream/android_frameworks_base/commit/0f9e9e23c79600538a48ad74c90c82e76aaf7743

**Comment by Abhinavgupta371** [comment]
@Keertesh19 Pruu

**Pull request closed without merging**
